# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build
on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 21
          cache: 'gradle'

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/

  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: checkstyle
        uses: nikitasavinov/checkstyle-action@0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: "checkstyle.xml"
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-check' || 'github-check' }}
